app/users/routes.py
import os
from PIL import Image
import secrets
from datetime import datetime

from flask_mail import Message
from flask import (
    render_template, url_for, redirect,
    flash, request, Blueprint, abort,
    jsonify,session)
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import or_ , and_

from .forms import (
    RegistrationForm, LoginForm, UpdateAccountForm,
    CommentForm, RequestResetForm,
    ResetPasswordForm, SupportForm)
from .models import (
    User, UserFavorite, UserComments,
    SupportMessage, UserFavoriteCategory,
    Friendship, UserActivities, UserMessages)
from .. import bcrypt, mail, db
from ..meals.models import Meal, Ingredient, Category, Area, MealIngredient
from .scripts.logic import sort_ingrs_by_alphabet , calculate_user_status

satatic_path = os.path.abspath(
    os.path.join(
        os.path.dirname(
            os.path.abspath(__file__)), 'static'))

users_bp = Blueprint(
    'users',
    __name__,
    template_folder='templates',
    url_prefix='/user',
    static_folder='static',
    static_url_path=satatic_path
)


@users_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)

        db.session.add(user)
        db.session.commit()
        flash(
            'Your account has been created! You are now able to log in',
            'success')

        # User Activity
        user = User.query.filter_by(email=form.email.data).first()
        user_activity = UserActivities(user_id=user.id)
        db.session.add(user_activity)
        db.session.commit()

        return redirect(url_for('users.login'))
    return render_template('register.html',
                           title='Register',
                           form=form)


@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password,
                form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')

            # User Activity
            user_activity = UserActivities.query.filter_by(
                user_id=current_user.id).first()
            user_activity.login += 1

            db.session.commit()
            return redirect(next_page) \
                if next_page \
                else redirect(url_for('index.index'))
        else:
            flash(
                'Login Unsuccessful. Please check email and password',
                'danger')

    return render_template('login.html',
                           title='Login', form=form)


@users_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index.index'))


def save_prof_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(
        users_bp.root_path,
        'static/profile_pics',
        picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


@users_bp.route('/account', methods=['POST'])
@login_required
def account_post():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        data_not_changed = (current_user.username != form.username.data)
        if not data_not_changed and not form.picture.data:
            flash("No changes", 'success')
        else:
            if data_not_changed:
                current_user.username = form.username.data
                current_user.email = form.email.data
            elif form.picture.data:
                picture_file = save_prof_picture(form.picture.data)
                current_user.image_file = picture_file

            # User Activity
            user_activity = UserActivities.query.filter_by(
                user_id=current_user.id).first()
            user_activity.profile_pict += 1

            db.session.commit()
            flash("Your account has been updated", 'success')
        return redirect(url_for('users.account_get'))

    return redirect(url_for('users.account_get'))


@users_bp.route('/account', methods=['GET'])
@login_required
def account_get():
    form = UpdateAccountForm()
    form.username.data = current_user.username
    form.email.data = current_user.email
    image_file = url_for(
        'users.static',
        filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html',
                           title='Account', image_file=image_file, form=form)


@users_bp.route('/new_recipe', methods=["GET"])
@login_required
def new_recipe_get():
    context = {
        'ingr': Ingredient.query.all(),
        'areas': Area.query.all(),
        'categ': Category.query.all(),
    }
    alphabetic_sorted_ingrs = sort_ingrs_by_alphabet(context['ingr'])

    return render_template(
        'new_recipe.html',
        title='New Post',
        legend='New Post',
        context=context,
        alp=alphabetic_sorted_ingrs)


@users_bp.route('/new_recipe', methods=["POST"])
@login_required
def new_recipe_post():
    context = {
        'ingr': Ingredient.query.all(),
        'areas': Area.query.all(),
        'categ': Category.query.all(),
    }

    alphabetic_sorted_ingrs = sort_ingrs_by_alphabet(context['ingr'])
    meal_info = {
        'name': request.form.get('title'),
        'instruction': request.form.get('content'),
        'country': request.form.get('area'),
        'category': request.form.get('category'),
        'ingredients': request.form.getlist('ingredients'),
    }

    # validate data
    if meal_info['name'] and meal_info['instruction'] and \
            meal_info['country'] and meal_info['category'] and \
            meal_info['ingredients']:
        meal = Meal(
            id=Meal.query.order_by(Meal.id.desc()).first().id + 1,
            name=meal_info['name'],
            category_id=Category.query.filter_by(
                name=meal_info['category']).first().id,
            area_id=Area.query.filter_by(name=meal_info['country']).first().id,
            author_id=current_user.id,
            instructions=meal_info['instruction'],
            tags=None,
            video_link=None,
        )
        db.session.add(meal)
        for x in meal_info['ingredients']:
            meal_ingr = MealIngredient(by_user=1,
                                        meal_id=meal.id,
                                        ingredient_id=Ingredient.query.
                                        filter_by(
                                            name=x).first().id)
            db.session.add(meal_ingr)
            db.session.commit()

        # User Activity
        user_activity = UserActivities.query.filter_by(
            user_id=current_user.id).first()
        user_activity.meal_author += 1
        db.session.commit()

        return redirect(url_for('meals.meal_info', m_id=meal.id))

    else:
        error = 'Please fill all Fields '
        return render_template(
            'new_recipe.html',
            title='New Post',
            legend='New Post',
            context=context,
            error=error,
            alp=alphabetic_sorted_ingrs)


@users_bp.route('/favourites', methods=['GET'])
@login_required
def favourites():
    return render_template('favourites.html')


@users_bp.route('/user_profile/<int:u_id>', methods=['GET'])
@login_required
def users_profiles(u_id: int):
    user_extra = db.session.query(User).all()
    user = db.session.query(User). \
        filter(User.id.like(u_id)).first()
    user_favorite_meals = db.session.query(UserFavorite). \
        filter(UserFavorite.user_id.like(u_id)).all()
    user_meals = db.session.query(Meal). \
        filter(Meal.author_id.like(u_id)).all()
    comments = db.session.query(UserComments). \
        filter(UserComments.user_id.like(u_id)).all()
    favorite_categories = db.session.query(UserFavoriteCategory). \
        filter(UserFavoriteCategory.user_id.like(u_id)).all()
    friends = db.session.query(User). \
        join(Friendship, User.id == Friendship.requesting_user_id). \
        add_columns(Friendship.receiving_user_id,
                    Friendship.requesting_user_id).filter(
        or_(Friendship.requesting_user_id == u_id,
            Friendship.receiving_user_id == u_id),
        Friendship.status == 1).all()
    activitie = db.session.query(UserActivities).\
        filter(UserActivities.user_id==u_id).first()
    status = calculate_user_status(activitie.total)
    
    f_ship_requests = db.session.query(Friendship). \
        filter(
        Friendship.receiving_user_id.like(current_user.id),
        Friendship.status.is_(False)).all()
    check_fship = None
    if current_user.id != u_id:
        check_fship = db.session.query(Friendship). \
                          filter(
            Friendship.requesting_user_id.like(current_user.id),
            Friendship.receiving_user_id.like(
                u_id)).first() or db.session.query(Friendship). \
                          filter(

app/users/templates/chatroom.html

<style>
.chatmsg{
    color:#393939;
    font-family:sans-serif;
    font-weight:400;
    font-size:14px;
    margin :10px;
    line-height:17px;
}
.chatleft{
   margin-left:250px;
   background:#455394;
   width:200px;
   height:60px;
   border-radius:15px;
   padding:10px;
   color:#fff;
}
.chatright{
    background:#393939;
   width:200px;
   height:60px;
   border-radius:10px;
   padding:10px;
   color:#fff;
}
.posttime{
    font-size:12px;
    display:block;
}
.img_file{
    width: 32px;
    height: 32px;
    margin-top: -22px;
    margin-left: -18px;
}
.chatnow{
    background:#72d69a;
    margin-left:100px;
   width:200px;
   height:60px;
   border-radius:10px;
   padding:10px;
   color:#fff;
}
</style>

<head>
  <title>YummyMeals - Private Messages</title>
</head>

<h2>Friends chat</h2>
<div id = "messagelist"style="width:500px;margin:0px auto;height:300px;overflow-y:scroll">
{% for m in messagesList %}
    <div class="chatmsg 
        {% if m.sender.username == current_user.username %}chatleft{% else %} chatright{% endif %}">

    <a href="{{url_for('users.users_profiles',u_id=m.sender.id)}}"><img class = "img_file" src={{url_for('users.static' ,filename="profile_pics/"+m.sender.image_file)}}></img></a>
    
    <span>
        {{m.content}}
    </span>
    <span class="posttime">{{m.send_date|timeagofilter}}</span>
    </div>

{% endfor %}
</div>

    <script src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>

<script type="text/javascript" charset="utf-8">
            $('#messagelist').scrollTop($('#messagelist')[0].scrollHeight)
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port+'/user/chatroom/'+"{{room}}/");
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('user_text', function(data) { 
                    console.log(123)
                        
                        $('#messagelist').append($('<p class="chatmsg chatnow">').append($('<em>').text(data.msg))); 
                        $('#messagelist').scrollTop($('#messagelist')[0].scrollHeight)
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
        </script>

    <input  id="text" size="80" placeholder="Enter your message here" style="width:200px; height:35px;margin:0 35%;"><br><br>


app/users/templates/comments1.html
{% extends 'base.html' %}
{% block content %}
    {% for comment in comments %}
      <article class="media content-section">
          <img class="rounded_circle article-img" src="{{url_for('users.static' ,filename='profile_pics/'+comment.user.image_file ) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" >{{ comment.author.username }}</a>
            <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if comment.author == current_user %}
              <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('users.update_comment', comment_id=comment.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
              </div>
            <!-- Modal -->
              <div class="modal fade " id="deleteModal" tabindex="1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" style = "margin: 120px auto; z-index:10;" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <form action="{{ url_for('users.delete_comment', comment_id=comment.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ comment.title }}</h2>
          <p class="article-content">{{ comment.content }}</p>
        </div>
      </article>

{% endfor %}

{% endblock content %}

app/users/templates/favourites.html
{% extends "base.html" %}
{% block content %}
    <br>
    <h1>HERE WILL BE MY FAVOURITE LIST</h1>
{% endblock content %}

app/users/templates/login.html
{% extends  'base.html'   %}
{% block content %}  

<style>
.content-section{width:40%;margin:0 auto; }

</style>

    <div class="content-section" >
    {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
    {{message[1]}}
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
	<br>
	<div class="profile-header-background" style="background:url({{url_for('users.static' , filename = "profile_pics/Login3.png")}}); width:100%; height:420px;background-size:cover;margin:0px auto;opacity:0.8;"></div> 
          <form method="POST" action="">
            {{ form.hidden_tag() }}
			<br><br>
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}<br><br>
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
		    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    </div>
<br><br><br><br><br><br><br><br><br><br>
{% endblock content %}


app/users/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}

    
<link rel="stylesheet" href= {{url_for('users.static' , filename = "user_profile.css" ) }} > </link>
<div class="container">   
    <div class="user-profile">
        <div class="profile-header-background" style="background:url({{url_for('meals.static' , filename = "default.jpg")}}); width:100%; height:350px;background-size:cover;margin:0px auto;"></div> 
        <div class="row">
            <div class="col-md-4">
                <div class="profile-info-left">
                    <div class="text-center">
                        <img src="{{url_for('users.static' ,filename='profile_pics/'+user.image_file) }}" alt="Avatar" class="avatar img-circle">
                                
                          <h2>{{user.username}} 
                            {% if status %}
                                 <span class="badge badge-primary" style="color: #72d69a;
                                                                                                background: #011b1fd9;">
                                    {{status}}
                                </span>
                            {% endif %}
                        </h2>
                    </div>
                     <div class="action-buttons">
                        <div class="row">
                        {% if user.id == current_user.id %}
                           <div class="col-xs-6">
                                <a href="{{url_for('users.account_get')}}" class="btn btn-success btn-block"><i class="fa fa-plus-round"></i> Settings </a>
                            </div>
                        {% endif %}

                        {% if  user.id != current_user.id and not check_fship %}
                            <div class="col-xs-6">
                                <a href="{{url_for('users.add_to_friends' , f_id = user.id)}}" class="btn btn-primary"><i class="fa fa-plus-round"></i> Send friend request</a>
                            </div> 
                        {% elif user.id != current_user.id and  not check_fship.status %}
                             <div class="col-xs-6">
                                <a href="{{url_for('users.add_to_friends' , f_id = user.id)}}" class="btn btn-danger"><i class="fa fa-plus-round"></i> Remove friend request </a>
                            </div>
                        {% elif user.id != current_user.id and  check_fship.status %}
                            <div class="col-xs-6">
                                <a href="{{url_for('users.add_to_friends' , f_id = user.id)}}" class="btn btn-danger"><i class="fa fa-plus-round"></i> Remove from friends </a>
                            </div>
                        {% endif %}
                        
                        </div>
                    </div>
                    <div class="section">
                        <h3>About Me</h3>
                        <p>Email - {{user.email}} </p>
                    </div>
                    <div class="section">
                        <h3>Statistics</h3>
                        <p><span class="badge">{{user_meals|length}}</span> Recipe Added</p>
                        <p><span class="badge">{{ufm|length}}</span> Favorites Recipes</p>
                        <p><span class="badge">{{comments|length}}</span> Comments</p>
                        <p><span class="badge">{{ufc|length}}</span> Favorites Categories</p>
			<p><span class="badge">{{friends|length}}</span> Friends</p>    
                    </div>
                    <div class="section">
                        <h3>Social</h3>
			{%if f_ship_requests %}
				<br>
				<a href="{{url_for('users.user_friend_requests')}}">A friend request is awaiting for your approval!<br><br></a>
			{%endif%}
			<style>	#more {display: none;}	</style>
			<p><span id="dots"></span><span id="more">
                         {% for usr in user_extra %}
                          	{% if usr.id != current_user.id %}
                          		<a href="{{url_for('users.users_profiles', u_id = usr.id)}}">{{usr.username}}<br></a>
                          	{% endif%}
                          {% endfor %}
                          <br>
                          </span></p>
                          <button onclick="myFunction()" id="myBtn">Click to expand our users list</button>

                          <script>
                          function myFunction() {
                            var dots = document.getElementById("dots");
                            var moreText = document.getElementById("more");
                            var btnText = document.getElementById("myBtn");
                          
                            if (dots.style.display === "none") {
                              dots.style.display = "inline";
                              btnText.innerHTML = "Click to expand our users list"; 
                              moreText.style.display = "none";
                            } else {
                              dots.style.display = "none";
                              btnText.innerHTML = "Close"; 
                              moreText.style.display = "inline";
                            }
                          }
                          </script>
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
                        <ul class="list-unstyled list-social">

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="profile-info-right">
                    <ul class="nav nav-pills nav-pills-custom-minimal custom-minimal-bottom">
                        <li class="active"><a href="#activities" data-toggle="tab">Comments</a></li>
                        <li><a href="#followers" data-toggle="tab">My Favorite Recipes</a></li>
                        <li><a href="#following" data-toggle="tab">My Recipes</a></li>  
                        <li><a href="#followed" data-toggle="tab">Favorite Categories</a></li>
			<li><a href="#friendy" data-toggle="tab">Friends</a></li>
                    </ul>
                    <div class="tab-content">
                        <!-- activities -->
                                 <div class="tab-pane fade in active" id="activities">

                       {% for comment in comments %}
                            <div class="media activity-item">
                                <a href="#" class="pull-left">
                                    <img src={% if comment.meal.author_id != 1%}{{url_for('meals.static' , filename = comment.meal.img_link )}}{% else %}{{comment.meal.img_link}}{% endif %} alt="Avatar" class="media-object avatar">
                                </a>
                                <div class="media-body">
                                    <p class="activity-title"><a href="{{url_for('users.users_profiles', u_id=u_id)}}">{{user.username}}</a> comment <a href="{{url_for('meals.meal_info' , m_id = comment.meal.id )}}"> {{comment.meal.name}} </a> <small class="text-muted">- {{comment.date_posted|timeagofilter}}</small></p>
                                    <small class="text-muted">{{comment.date_posted|formatdatetime}}</small>
                                </div>
                            </div>
                       
                       {% endfor %}
                       </div>
                        <!-- followers -->
                        <div class="tab-pane fade" id="followers">
                        {% for favorite in ufm %}  
                            <div class="media user-follower">
                                <img src="{% if favorite.meal.author_id != 1%}{{url_for('meals.static' , filename = favorite.meal.img_link )}}{% else %}{{favorite.meal.img_link}}{% endif %}" class="media-object pull-left">
                                <div class="media-body">
                                    <a href="{{url_for('meals.meal_info' , m_id = favorite.meal.id)}}">{{favorite.meal.name}}<br><span class="text-muted username">@{{favorite.meal.category.name}}</span></a>

                                        {% if current_user.id == user.id %}
                                                <a  style = "color:#fff" href = "{{url_for('meals.add_favorite' , meal_id = favorite.meal.id)}} " type="button" class="btn btn-sm btn-toggle-following pull-right"><i class="fa fa-checkmark-round"></i> <span>Remove</span></a>
                                        {% endif %}

                                </div>
                            </div>
                        {% endfor %}
                        </div>
                        
                        <!-- end followers -->
                        <!-- following -->
                        <div class="tab-pane fade" id="following">
                        {% for meal in user_meals %}
                            <div class="media user-following">
                                    <img src={% if meal.author_id != 1%}{{url_for('meals.static' , filename = meal.img_link )}}{% else %}{{meal.img_link}}{% endif %} alt="User Avatar" class="media-object pull-left">
                                    <div class="media-body">
                                        <a href="{{url_for('meals.meal_info'  , m_id = meal.id)}}">{{meal.name}}<br><span class="text-muted username">@{{meal.category.name}}</span></a>
                                       {% if current_user.id == user.id %}
                                            <!--
                                         <a href="{{url_for('users.remove_meal' , m_id = meal.id , u_id = user.id)}}" style="color:#fff" type="button" class="btn btn-sm btn-danger pull-right"><i class="fa fa-close-round"></i> Delete </a>
                                            -->
                                       {% endif %}
                                    
                                    </div>
                            </div>
                        {% endfor %}

                        </div>
                        <!-- end following -->
                 <!-- followed -->
                        <div class="tab-pane fade" id="followed">
                        {% for favorite in ufc %} 
 
                            <div class="media user-follower">
                                <img src="{{favorite.category.img_link}}" class="media-object pull-left">
								<div class="media-body">
								<a href="{{url_for('meals.meals_by_category', c_id = favorite.category_id)}}">@{{favorite.category.name}}<br><span class="text-muted username"</a>

                                        {% if current_user.id == user.id %}
                                                <a  style = "color:#fff" href = "{{url_for('meals.add_favorite_category' , category_id = favorite.category_id)}} " type="button" class="btn btn-sm btn-toggle-following pull-right"><i class="fa fa-checkmark-round"></i> <span>Remove</span></a>
                                        {% endif %}
								</div>
                                
                            </div>
                        {% endfor %}
                        </div>
                        
                        <!-- end followed -->
			<!-- friendy -->
			<div class="tab-pane fade" id="friendy">
                        {% for fellow in friends %} 
              		<div class="media user-follower">
			<div class="media-body">
				{% if u_id == fellow.receiving_user_id %}
					<img src="{{url_for('users.static' ,  filename='profile_pics/'+fellow[0].image_file) }}" alt="Avatar" class="avatar img-circle">
					<a href="{{url_for('users.users_profiles', u_id = fellow.requesting_user_id)}}">{{fellow[0].username}}<br><span class="text-muted username"</a>
            					{%else%}										
							{%for usr in user_extra%}
							{% if usr.id == fellow.receiving_user_id%}																
								<img src="{{url_for('users.static' ,  filename='profile_pics/'+usr.image_file) }}" alt="Avatar" class="avatar img-circle">										
								<a href="{{url_for('users.users_profiles', u_id = fellow.receiving_user_id)}}">{{usr.username}}<br><span class="text-muted username"</a>
							{%endif%}
							{%endfor %}			
					{% endif%}
				</div>                                
                            </div>
                        {% endfor %}
                        </div>
                        <!-- end friendly-->	

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}